fix(ci): add jira integration
Jira-Id: VPNAPPL-2329

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -55,7 +55,7 @@ include:
     inputs:
       output_directory: apple-vpn-ci
       cmd_prefix: "mint run "
-      templates: "pages.docc fastlane $PIPELINE_TEMPLATE slack-message.txt sparkle-item.xml"
+      templates: "$PIPELINE_TEMPLATE pages.docc fastlane slack-message.txt sparkle-item.xml issue-hashes.txt"
       trains: "ios mac tv"
 
 ##
@@ -136,6 +136,21 @@ prepare:
           Integration/Scripts/lint_translations.sh # Lint string files
       fi
     - !reference [.lhc_describe, script] # Generate child pipelines
+    - | # Use template output to fetch workflow information, and update the repo (don't require success)
+      if [ -n "$CI_MERGE_REQUEST_IID" ]; then
+        Integration/Scripts/update_workflow_metadata.sh || true
+      elif [ -n "$CI_COMMIT_TAG" ]; then
+        Integration/Scripts/update_workflow_metadata.sh "$DESCRIBE_DIR/release/issue-hashes.txt" || true
+      else
+        Integration/Scripts/update_workflow_metadata.sh \
+            "$DESCRIBE_DIR/mac/issue-hashes.txt" \
+            "$DESCRIBE_DIR/ios/issue-hashes.txt" \
+            "$DESCRIBE_DIR/tv/issue-hashes.txt" \
+          || true
+      fi
+
+      # Don't fail if push doesn't work, there will be plenty of opportunities to update in a later pipeline
+      git push origin refs/notes/proton/attrs || true
   rules:
     - if: $CI_MERGE_REQUEST_TITLE =~ /^Draft:/ # Don't run pipelines automatically for draft MRs
       when: manual
